[package]
authors = ["Jonas Platte <jplatte+git@posteo.de>"]
categories = ["api-bindings", "web-programming"]
description = "Types for the endpoints in the Matrix server-server API."
documentation = "https://docs.rs/ruma-federation-api"
edition = "2018"
homepage = "https://github.com/ruma/ruma-federation-api"
keywords = ["matrix", "chat", "messaging", "ruma"]
license = "MIT"
name = "ruma-federation-api"
readme = "README.md"
repository = "https://github.com/ruma/ruma-federation-api"
version = "0.0.1"

[dependencies]
js_int = "0.1.4"
ruma-api = "0.16.0-rc.3"
ruma-events = "0.21.0-beta.1"
ruma-identifiers = "0.16.0"
ruma-serde = "0.1.0"
serde = { version = "1.0.106", features = ["derive"] }
serde_json = "1.0.51"
